# **Pytorch Tutorial**


In [1]:
import torch

**1. Pytorch Documentation Explanation with torch.max**

torch.randn(4, 5) 會建立一個 4 行 5 列的矩陣，裡面的數值從標準常態分佈（mean=0, std=1）隨機取樣。

可以傳入更多參數來建立更高維度的張量，例如 torch.randn(2, 4, 5) 是 2 個 4×5 的矩陣

另一常見的函數有 torch.rand，範圍是 [0, 1)，亦常用於初始化神經網路的權重。

In [2]:
x = torch.randn(4,5)
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[ 2.4582,  0.7153,  0.5614,  0.6513, -1.5068],
        [-1.2489, -0.2355,  1.9753,  0.7550, -1.0953],
        [ 0.7067,  0.0404,  0.5575, -0.8428, -0.1566],
        [-0.9308,  1.3599, -1.5608,  0.3811, -1.1231]])
tensor([[-0.8398,  0.1425, -1.3495, -0.7956,  0.2668],
        [ 0.8971,  1.0618,  0.8139, -0.7415,  1.1994],
        [ 0.7688,  0.6186, -0.0485,  1.1992, -1.0618],
        [ 0.9848, -1.0290,  0.3324, -0.4957, -0.8546]])
tensor([[-1.6819,  1.4303,  0.6011, -0.1375, -0.3349],
        [ 0.3075,  0.7314,  1.3362,  0.2522, -1.1333],
        [-1.0943,  1.1005, -0.7831,  0.8584, -0.9280],
        [-0.7146,  0.9436, -0.2451, -1.3492, -1.3349]])


In [3]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(2.4582)


In [4]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0)
print(m)
print(idx)

tensor([ 2.4582,  1.3599,  1.9753,  0.7550, -0.1566])
tensor([0, 3, 1, 1, 2])


In [5]:
# 2-2
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([ 2.4582,  1.3599,  1.9753,  0.7550, -0.1566])
tensor([0, 3, 1, 1, 2])


In [6]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([ 2.4582,  1.3599,  1.9753,  0.7550, -0.1566])
tensor([0, 3, 1, 1, 2])


In [7]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
print(m)
print(idx)

tensor([[ 2.4582,  1.3599,  1.9753,  0.7550, -0.1566]])
tensor([[0, 3, 1, 1, 2]])


In [8]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([ 2.4582,  1.3599,  1.9753,  0.7550, -0.1566])
tensor([0, 3, 1, 1, 2])


/tmp/ipykernel_11724/1447715753.py:3: UserWarning: An output with one or more elements was resized since it had shape [1, 5], which does not match the required output shape [5]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /pytorch/aten/src/ATen/native/Resize.cpp:31.)
  torch.max(x,0,False,out=p)


In [9]:
# 2-6
p = (m,idx)
torch.max(x,0,False,p)
print(p[0])
print(p[1])

TypeError: max() received an invalid combination of arguments - got (Tensor, int, bool, tuple), but expected one of:
 * (Tensor input, *, Tensor out = None)
 * (Tensor input, Tensor other, *, Tensor out = None)
      didn't match because some of the arguments have invalid types: (Tensor, !int!, !bool!, !tuple of (Tensor, Tensor)!)
 * (Tensor input, int dim, bool keepdim = False, *, tuple of Tensors out = None)
 * (Tensor input, name dim, bool keepdim = False, *, tuple of Tensors out = None)


In [10]:
# 2-7
m, idx = torch.max(x,True)

TypeError: max() received an invalid combination of arguments - got (Tensor, bool), but expected one of:
 * (Tensor input, *, Tensor out = None)
 * (Tensor input, Tensor other, *, Tensor out = None)
 * (Tensor input, int dim, bool keepdim = False, *, tuple of Tensors out = None)
 * (Tensor input, name dim, bool keepdim = False, *, tuple of Tensors out = None)


In [11]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t = torch.max(x,y)
print(t)

tensor([[ 2.4582,  0.7153,  0.5614,  0.6513,  0.2668],
        [ 0.8971,  1.0618,  1.9753,  0.7550,  1.1994],
        [ 0.7688,  0.6186,  0.5575,  1.1992, -0.1566],
        [ 0.9848,  1.3599,  0.3324,  0.3811, -0.8546]])


**2. Common errors**



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.

在 PyTorch 中，device 指的是張量（tensor）或模型存放在哪個硬體上執行運算。CPU 和 GPU 是實體上不同的記憶體空間，就像兩台不同的電腦，資料不能直接相加。

常見的 device：
"cpu": 一般 CPU，電腦預設
"cuda:0": 第一張 NVIDIA GPU
"cuda:1": 第二張 NVIDIA GPU
"mps": Apple Silicon GPU（M1/M2/M3）


In [ ]:
import torch

In [12]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cpu")
y = model(x)

RuntimeError: Expected all tensors to be on the same device, but got mat1 is on cpu, different from other tensors on cuda:0 (when checking argument in method wrapper_CUDA_addmm)

In [13]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

torch.Size([1])


In [ ]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y= torch.randn(5,4)
z = x + y

RuntimeError: ignored

In [ ]:
# 2. mismatched dimensions error (fixed)
y= y.transpose(0,1)
z = x + y
print(z.shape)

torch.Size([4, 5])


In [ ]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (512 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)


RuntimeError: ignored

In [ ]:
# 3. cuda out of memory error (fixed)
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0))
print(out.shape)


# 這樣做雖然省記憶體，但速度很慢
# GPU 的優勢就是平行處理大量資料，一次只跑一張無法發揮 GPU 效能。
# 實務上會用適當的 batch size（如 32）來平衡記憶體和速度。

## 假設有 2048 張圖片
# data = torch.randn(2048, 3, 224, 224)

# batch_size = 32

# for i in range(0, len(data), batch_size):
#     batch = data[i : i + batch_size]          # 每次取 32 張
#     out = resnet18(batch.to("cuda:0"))         # 一次處理 32 張
#     print(f"batch {i//batch_size}: {out.shape}")

## 輸出：
## batch 0:  torch.Size([32, 1000])
## batch 1:  torch.Size([32, 1000])
## ...
## batch 63: torch.Size([32, 1000])  ← 共 64 個 batch（2048/32）


torch.Size([1, 1000])


In [ ]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0])
lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels

RuntimeError: ignored

In [ ]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)

tensor(2.6215)


**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [14]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [15]:
for datapoint in dataset:
  print(datapoint)

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array.



torch.utils.data.DataLoader will need two imformation to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [16]:
import torch
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['x']
['d']
['c']
['f']
['l']
['s']
['q']
['j']
['u']
['a']
['v']
['z']
['k']
['p']
['e']
['n']
['b']
['i']
['o']
['h']
['y']
['t']
['m']
['g']
['w']
['r']


A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [17]:
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['A']
['X']
['P']
['Y']
['Q']
['S']
['O']
['F']
['J']
['M']
['g']
['j']
['h']
['T']
['z']
['l']
['N']
['K']
['I']
['r']
['o']
['q']
['c']
['U']
['v']
['k']
['d']
['L']
['W']
['C']
['B']
['y']
['b']
['f']
['e']
['x']
['V']
['H']
['D']
['w']
['a']
['Z']
['u']
['E']
['p']
['G']
['R']
['s']
['i']
['n']
['m']
['t']
